install:
- pod repo update && pod install
osx_image: xcode8
language: objective-c
xcode_workspace: WordPressCom-Stats-iOS.xcworkspace
xcode_scheme: WordPressCom-Stats-iOS
xcode_sdk: iphonesimulator
sudo: false
