install:
- pod install
osx_image: xcode8
language: objective-c
sudo: false
script:
- set -o pipefail && xcodebuild -workspace WordPressCom-Stats-iOS.xcworkspace -scheme WordPressCom-Stats-iOS -sdk iphonesimulator | xcpretty
